# Generated by Django 6.0.4 on 2026-05-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_uq_categories_name_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='point_per_kg',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='price_per_kg',
            field=models.PositiveIntegerField(),
        ),
    ]
