# Generated by Django 6.0.4 on 2026-05-10 02:24

from django.db import migrations

def seed_levels(apps, schema_editor):
    Level = apps.get_model("gamification", "Level")

    levels = [
        {"name": "Seedling", "min_points": 0},
        {"name": "Sprout", "min_points": 100},
        {"name": "Green Keeper", "min_points": 300},
        {"name": "Eco Ranger", "min_points": 700},
        {"name": "Earth Guardian", "min_points": 1500},
        {"name": "Recycling Hero", "min_points": 3000},
        {"name": "Planet Protector", "min_points": 5000},
        {"name": "Sustainability Master", "min_points": 8000},
        {"name": "Eco Legend", "min_points": 12000},
        {"name": "Zero Waste Champion", "min_points": 20000},
    ]

    for level in levels:
        Level.objects.get_or_create(
            min_points=level["min_points"],
            defaults={
                "name": level["name"]
            }
        )

def reverse_seed_levels(apps, schema_editor):
    Level = apps.get_model("gamification", "Level")

    Level.objects.filter(
        min_points__in=[0, 1000, 3000, 7000]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_levels, reverse_seed_levels),
    ]
