# Generated by Django 6.0.4 on 2026-05-10 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_seed_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='min_points',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
