# Generated by Django 6.0.4 on 2026-05-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='point_per_kg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='price_per_kg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='total_point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
