# Generated by Django 6.0.4 on 2026-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactiondetail_point_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
