# Generated by Django 6.0.4 on 2026-04-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
