# Generated by Django 6.0.4 on 2026-04-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_role_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='permissions.permission'),
        ),
    ]
